name: weather_forecast
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.10
  provider: ^4.3.2+2
  http: ^0.12.2
  flutter_dotenv: ^2.1.0
  lottie: ^0.6.0
  flutter_launcher_icons: ^0.8.0
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - json/
    - .env
    - icon/

flutter_icons:
  android: true
  ios: true
  image_path: "icon/icon.png"
